version: '3.9'

services:
  db:
    image: mysql:latest
    restart: always
    networks:
      - backend
    env_file:
      - ./.env
    environment:
      - MYSQL_DB=${DB_NAME}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - 11037:11037
    networks:
      - backend
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      - MYSQL_DB=${DB_NAME}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

networks:
  backend:
    driver: bridge