version: '3.9'

services:
  db:
    image: mysql:latest
    restart: always
    networks:
      - backend
    env_file:
      - ./.env
    environment:
      - MYSQL_DB=${DB_NAME}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_HOST=${DB_HOST}
    ports:
      - 3306:3306

  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 11037:11037
    networks:
      - backend
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      - MYSQL_DB=${DB_NAME}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_HOST=${DB_HOST}

networks:
  backend:
    driver: bridge